"""AIL.5C fresh challenges: authored, versioned pools with deterministic draws.

The draw is a pure function of ``(learner, definition, attempt sequence)``:
the same inputs always produce the same challenge, so any attempt can be
reproduced and audited. Challenges are NEVER generated by a model; an
AI-generated challenge could not independently qualify DEMONSTRATED and this
module has no path that produces one.

There is no copy detection here — no similarity, token-overlap or
fingerprinting. Integrity comes from fresh, seeded, record-grounded challenges.
"""

import hashlib
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Set

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.assessment import AssessmentAttempt, AssessmentDefinition
from app.models.concepts import LearningItem
from app.services.review_attempt_service import choice_spec

GENERATOR = "authored_pool_v1"


@dataclass(frozen=True)
class ChallengeDraw:
    seed: str
    instance: Dict[str, Any]


def challenge_seed(user_id: str, definition_id: str, attempt_seq: int) -> str:
    return hashlib.sha256(f"{user_id}|{definition_id}|{attempt_seq}".encode()).hexdigest()


def _rank(seed: str, entry_key: str) -> str:
    return hashlib.sha256(f"{seed}|{entry_key}".encode()).hexdigest()


def previously_issued_keys(db: Session, user_id: str, definition_key: str) -> Set[str]:
    """Entry keys already issued to this learner for ANY version of the key."""
    rows = db.execute(
        select(AssessmentAttempt.challenge_instance)
        .join(AssessmentDefinition, AssessmentDefinition.id == AssessmentAttempt.definition_id)
        .where(AssessmentAttempt.user_id == user_id, AssessmentDefinition.definition_key == definition_key)
    ).scalars()
    keys: Set[str] = set()
    for instance in rows:
        for item in (instance or {}).get("items") or []:
            keys.add(item["entry_key"])
    return keys


def attempt_sequence(db: Session, user_id: str, definition_key: str) -> int:
    count = db.execute(
        select(AssessmentAttempt.id)
        .join(AssessmentDefinition, AssessmentDefinition.id == AssessmentAttempt.definition_id)
        .where(AssessmentAttempt.user_id == user_id, AssessmentDefinition.definition_key == definition_key)
    ).all()
    return len(count) + 1


def _resolve_entry(db: Session, entry: dict) -> Optional[dict]:
    """Inline entries pass through; ``learning_item_id`` entries are resolved
    to a frozen copy of a REVIEWED, deterministic choice item."""
    item_id = entry.get("learning_item_id")
    if not item_id:
        return entry
    item = db.get(LearningItem, item_id)
    spec = choice_spec(item) if item is not None and item.reviewed else None
    if spec is None:
        return None
    return {
        "entry_key": entry["entry_key"],
        "prompt": item.body_md or item.title,
        "options": spec["options"],
        "answer_key": spec["answer_key"],
        "multiple": spec["multiple"],
        "source": {"learning_item_id": item.id, "learning_item_version": item.version},
    }


def draw_challenge(
    db: Session, definition: AssessmentDefinition, user_id: str, *, exclude: Optional[Set[str]] = None
) -> Optional[ChallengeDraw]:
    """Deterministically draw from the definition's authored pool, or None
    when the definition has no challenge."""
    spec = definition.challenge_spec
    if not spec:
        return None
    seq = attempt_sequence(db, user_id, definition.definition_key)
    seed = challenge_seed(user_id, definition.id, seq)
    exclude = (
        exclude if exclude is not None else previously_issued_keys(db, user_id, definition.definition_key)
    )
    size = int(spec.get("draw_size", 1))

    resolved: List[dict] = [e for e in (_resolve_entry(db, e) for e in spec["pool"]) if e is not None]
    fresh = [e for e in resolved if e["entry_key"] not in exclude]
    exhausted = len(fresh) < size
    candidates = resolved if exhausted else fresh  # reseeded fallback only when the pool is used up
    if len(candidates) < size:
        return None
    drawn = sorted(candidates, key=lambda e: _rank(seed, e["entry_key"]))[:size]
    # Fixed entries (e.g. a capstone's explain-back questions) are always issued
    # alongside the seeded draw; they are authored, never generated.
    fixed = [e for e in (_resolve_entry(db, e) for e in spec.get("fixed") or []) if e is not None]

    items: List[dict] = []
    server_only: Dict[str, Any] = {"answer_keys": {}, "reference_points": {}, "values": {}}
    for entry in drawn + fixed:
        public = {
            k: v for k, v in entry.items() if k not in ("answer_key", "reference_points", "server_only")
        }
        if entry in fixed:
            public["fixed"] = True
        items.append(public)
        if "answer_key" in entry:
            server_only["answer_keys"][entry["entry_key"]] = sorted(entry["answer_key"])
        if entry.get("reference_points"):
            server_only["reference_points"][entry["entry_key"]] = list(entry["reference_points"])
        if entry.get("server_only"):
            server_only["values"][entry["entry_key"]] = entry["server_only"]

    first = drawn[0]
    instance = {
        "generator": GENERATOR,
        "entry_kind": spec.get("entry_kind", "variant"),
        "seed": seed,
        "attempt_sequence": seq,
        "pool_exhausted": exhausted,
        "items": items,
        # the first drawn entry's parameters, addressable by check specs
        "parameters": dict(first.get("parameters") or {}),
        "server_only": {**server_only, "values": dict(first.get("server_only") or {})},
        "per_entry_values": server_only["values"],
    }
    return ChallengeDraw(seed=seed, instance=instance)


def public_challenge(instance: Optional[dict]) -> Optional[dict]:
    """What the learner may see: never answer keys, reference points or
    server-only values."""
    if not instance:
        return None
    return {
        "entry_kind": instance.get("entry_kind"),
        "items": instance.get("items") or [],
        "parameters": instance.get("parameters") or {},
        "attempt_sequence": instance.get("attempt_sequence"),
        "generator": instance.get("generator"),
    }
