"""ma3 add model call provider request id

Revision ID: 60d932811e9b
Revises: fd9c450352e0
Create Date: 2026-09-16 17:08:26.426882

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60d932811e9b'
down_revision: Union[str, None] = 'fd9c450352e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_request_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_column('provider_request_id')

    # ### end Alembic commands ###
