"""ma5 add parallel comparison contract

Revision ID: 8791bbf48502
Revises: e0b0be06e2c5
Create Date: 2026-09-16 21:57:19.680310

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8791bbf48502"
down_revision: Union[str, None] = "e0b0be06e2c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_policy_override_json", sa.JSON(), nullable=True))

    with op.batch_alter_table("comparison_candidates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent_version_id", sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column("model_policy_override_json", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("review_config_json", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("task_run_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column("agent_run_id", existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.create_foreign_key(
            batch_op.f("fk_comparison_candidates_task_run_id_task_runs"), "task_runs", ["task_run_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_comparison_candidates_agent_version_id_agent_versions"),
            "agent_versions",
            ["agent_version_id"],
            ["id"],
        )

    with op.batch_alter_table("comparison_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("winner_artifact_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("winner_artifact_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("cancellation_requested_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_comparison_runs_winner_artifact_id_artifacts"),
            "artifacts",
            ["winner_artifact_id"],
            ["id"],
        )
        # Manually added -- Alembic's autogenerate comparator does not
        # detect CHECK constraint *body* changes on an existing Enum
        # column (only structural column/table changes).
        # ComparisonRunStatus gained a new "cancelled" value
        # (app.db.enums) with no other column change, so this
        # drop/recreate has to be hand-written. batch_op.f(...) marks the
        # name as already-final so the naming convention doesn't
        # re-prefix it (same fix as MA4's agentrunrole constraints).
        batch_op.drop_constraint(batch_op.f("ck_comparison_runs_comparisonrunstatus"), type_="check")
        batch_op.create_check_constraint(
            batch_op.f("ck_comparison_runs_comparisonrunstatus"),
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comparison_runs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_comparison_runs_comparisonrunstatus"), type_="check")
        batch_op.create_check_constraint(
            batch_op.f("ck_comparison_runs_comparisonrunstatus"),
            "status IN ('pending', 'running', 'completed', 'failed')",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_comparison_runs_winner_artifact_id_artifacts"), type_="foreignkey"
        )
        batch_op.drop_column("cancellation_requested_at")
        batch_op.drop_column("winner_artifact_hash")
        batch_op.drop_column("winner_artifact_id")

    with op.batch_alter_table("comparison_candidates", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_comparison_candidates_agent_version_id_agent_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_comparison_candidates_task_run_id_task_runs"), type_="foreignkey"
        )
        batch_op.alter_column("agent_run_id", existing_type=sa.VARCHAR(length=36), nullable=False)
        batch_op.drop_column("created_at")
        batch_op.drop_column("task_run_id")
        batch_op.drop_column("review_config_json")
        batch_op.drop_column("model_policy_override_json")
        batch_op.drop_column("agent_version_id")

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_column("model_policy_override_json")

    # ### end Alembic commands ###
