"""ail5b_build_with_me_foundation

Revision ID: 97c6dbe9ae3c
Revises: ail5a_academy_foundation
Create Date: 2026-09-24 20:56:43.640253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c6dbe9ae3c'
down_revision: Union[str, None] = 'ail5a_academy_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
    sa.Column('template_key', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('audience_level', sa.Enum('beginner', 'intermediate', 'advanced', name='projectaudiencelevel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ladder_level', sa.Enum('l0', 'l1', 'l2', 'l3', 'l4', name='projectladderlevel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('build_mode', sa.Enum('no_code', 'workflow', 'experiment', 'local_code', 'sandbox', name='projecttemplatebuildmode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('brief_md', sa.Text(), nullable=False),
    sa.Column('difficulty_profile_json', sa.JSON(), nullable=False),
    sa.Column('evidence_requirements_json', sa.JSON(), nullable=False),
    sa.Column('variant_spec_json', sa.JSON(), nullable=True),
    sa.Column('requires_platform_capability', sa.String(length=120), nullable=True),
    sa.Column('est_minutes_min', sa.Integer(), nullable=False),
    sa.Column('est_minutes_max', sa.Integer(), nullable=False),
    sa.Column('capstone_eligible', sa.Boolean(), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_project_templates_author_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_templates')),
    sa.UniqueConstraint('template_key', 'version', name='uq_project_templates_key_version')
    )
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_templates_template_key'), ['template_key'], unique=False)

    op.create_table('project_milestones',
    sa.Column('project_template_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions_md', sa.Text(), nullable=False),
    sa.Column('check_spec_json', sa.JSON(), nullable=False),
    sa.Column('learning_item_id', sa.String(length=36), nullable=True),
    sa.Column('expected_artifact_kind', sa.String(length=80), nullable=True),
    sa.Column('evidence_type', sa.String(length=80), nullable=True),
    sa.Column('reference_solution_ref', sa.String(length=255), nullable=True),
    sa.Column('hint_content_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], name=op.f('fk_project_milestones_learning_item_id_learning_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], name=op.f('fk_project_milestones_project_template_id_project_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_milestones')),
    sa.UniqueConstraint('project_template_id', 'position', name='uq_project_milestones_template_position')
    )
    op.create_table('project_template_concepts',
    sa.Column('project_template_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_project_template_concepts_concept_id_concepts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], name=op.f('fk_project_template_concepts_project_template_id_project_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_template_concepts')),
    sa.UniqueConstraint('project_template_id', 'concept_id', name='uq_project_template_concepts')
    )
    op.create_table('project_attempts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_template_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('is_capstone', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'declined', 'active', 'submitted', 'passed', 'needs_work', 'abandoned', name='projectattemptstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('brief_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('learner_agent_id', sa.String(length=36), nullable=True),
    sa.Column('app_eval_set_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_eval_set_id'], ['eval_sets.id'], name=op.f('fk_project_attempts_app_eval_set_id_eval_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_project_attempts_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_agent_id'], ['agents.id'], name=op.f('fk_project_attempts_learner_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], name=op.f('fk_project_attempts_project_template_id_project_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_attempts')),
    sa.UniqueConstraint('user_id', 'project_template_id', 'enrollment_id', 'is_capstone', name='uq_project_attempts')
    )
    with op.batch_alter_table('project_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('milestone_attempts',
    sa.Column('project_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('project_milestone_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'checking', 'passed', 'failed', 'skipped_study_mode', name='milestoneattemptstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('max_assistance_level', sa.Enum('h0', 'h1', 'h2', 'h3', 'h4', 'h5', name='assistancelevel', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('mode', sa.Enum('normal', 'challenge', 'study', 'variant', name='milestoneattemptmode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_attempt_id'], ['project_attempts.id'], name=op.f('fk_milestone_attempts_project_attempt_id_project_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_milestone_id'], ['project_milestones.id'], name=op.f('fk_milestone_attempts_project_milestone_id_project_milestones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_attempts')),
    sa.UniqueConstraint('project_attempt_id', 'project_milestone_id', name='uq_milestone_attempts')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_attempt_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('enrollment_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('agent_run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_artifacts_milestone_attempt_id_milestone_attempts'), 'milestone_attempts', ['milestone_attempt_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_artifacts_enrollment_id_enrollments'), 'enrollments', ['enrollment_id'], ['id'])

    with op.batch_alter_table('comparison_runs', schema=None) as batch_op:
        # AIL.3B added this column on SQLite without a named FK.  Do not
        # drop a constraint that does not exist on disposable fresh chains.
        batch_op.create_foreign_key(batch_op.f('fk_comparison_runs_experiment_id_experiments'), 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('development_concepts', schema=None) as batch_op:
        batch_op.drop_index('ix_development_concepts_concept_id')
        batch_op.drop_index('ix_development_concepts_development_state')
        batch_op.drop_constraint('fk_development_concepts_development_id_developments', type_='foreignkey')
        batch_op.drop_constraint('fk_development_concepts_concept_id_concepts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_development_concepts_development_id_developments'), 'developments', ['development_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_development_concepts_concept_id_concepts'), 'concepts', ['concept_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_shared_with_author', sa.Boolean(), nullable=False))

    with op.batch_alter_table('learner_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_mode', sa.Enum('beginner', 'intermediate', 'advanced', name='learnerexperiencemode', native_enum=False, create_constraint=True), nullable=True))
        batch_op.add_column(sa.Column('coding_comfort', sa.Enum('none', 'some', 'comfortable', name='learnercodingcomfort', native_enum=False, create_constraint=True), nullable=True))
        batch_op.add_column(sa.Column('career_goal_term_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('build_path', sa.Enum('no_code', 'code', name='learnerbuildpath', native_enum=False, create_constraint=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_learner_profiles_career_goal_term_id_taxonomy_terms'), 'taxonomy_terms', ['career_goal_term_id'], ['id'])

    with op.batch_alter_table('learning_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistance_level', sa.Enum('h0', 'h1', 'h2', 'h3', 'h4', 'h5', name='assistancelevel', native_enum=False, create_constraint=True), nullable=True))
        batch_op.add_column(sa.Column('execution_verification', sa.Enum('platform_verified', 'sandbox_verified', 'self_reported', 'not_applicable', name='executionverification', native_enum=False, create_constraint=True), nullable=True))
        batch_op.add_column(sa.Column('milestone_attempt_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_learning_evidence_milestone_attempt_id_milestone_attempts'), 'milestone_attempts', ['milestone_attempt_id'], ['id'])

    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        # AIL.3A likewise added experiment_id without a named SQLite FK.
        batch_op.create_foreign_key(batch_op.f('fk_task_runs_experiment_id_experiments'), 'experiments', ['experiment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        # No named constraint existed on the pre-5B SQLite schema.
        batch_op.create_foreign_key(None, 'experiments', ['experiment_id'], ['id'])

    with op.batch_alter_table('learning_evidence', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_learning_evidence_milestone_attempt_id_milestone_attempts'), type_='foreignkey')
        batch_op.drop_column('milestone_attempt_id')
        batch_op.drop_column('execution_verification')
        batch_op.drop_column('assistance_level')

    with op.batch_alter_table('learner_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_learner_profiles_career_goal_term_id_taxonomy_terms'), type_='foreignkey')
        batch_op.drop_column('build_path')
        batch_op.drop_column('career_goal_term_id')
        batch_op.drop_column('coding_comfort')
        batch_op.drop_column('experience_mode')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('progress_shared_with_author')

    with op.batch_alter_table('development_concepts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_development_concepts_concept_id_concepts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_development_concepts_development_id_developments'), type_='foreignkey')
        batch_op.create_foreign_key('fk_development_concepts_concept_id_concepts', 'concepts', ['concept_id'], ['id'])
        batch_op.create_foreign_key('fk_development_concepts_development_id_developments', 'developments', ['development_id'], ['id'])
        batch_op.create_index('ix_development_concepts_development_state', ['development_id', 'state'], unique=False)
        batch_op.create_index('ix_development_concepts_concept_id', ['concept_id'], unique=False)

    with op.batch_alter_table('comparison_runs', schema=None) as batch_op:
        # No named constraint existed on the pre-5B SQLite schema.
        batch_op.create_foreign_key(None, 'experiments', ['experiment_id'], ['id'])

    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_artifacts_enrollment_id_enrollments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_artifacts_milestone_attempt_id_milestone_attempts'), type_='foreignkey')
        batch_op.alter_column('agent_run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('enrollment_id')
        batch_op.drop_column('milestone_attempt_id')

    op.drop_table('milestone_attempts')
    with op.batch_alter_table('project_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_attempts_user_id'))

    op.drop_table('project_attempts')
    op.drop_table('project_template_concepts')
    op.drop_table('project_milestones')
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_templates_template_key'))

    op.drop_table('project_templates')
    # ### end Alembic commands ###
