"""ma2 add provider catalog refresh

Revision ID: 98b1b2919d8a
Revises: dc6427b0a95a
Create Date: 2026-09-16 16:22:11.569194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b1b2919d8a'
down_revision: Union[str, None] = 'dc6427b0a95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_catalog_refreshes',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='catalogrefreshstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('models_discovered', sa.Integer(), nullable=False),
    sa.Column('models_added', sa.Integer(), nullable=False),
    sa.Column('models_updated', sa.Integer(), nullable=False),
    sa.Column('models_unavailable', sa.Integer(), nullable=False),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_catalog_refreshes_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_catalog_refreshes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_catalog_refreshes')
    # ### end Alembic commands ###
