"""ma6 slice 3a evaluator provenance schema

Revision ID: bd27cdb01c15
Revises: 4ce24c918822
Create Date: 2026-09-17 20:38:00.066654

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd27cdb01c15"
down_revision: Union[str, None] = "4ce24c918822"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MA4's own agent_review migration already hit this: SQLite batch-mode
    # can leave *two* physical CHECK constraints on agent_runs.role from
    # when the column was first added -- one auto-named by the Enum type
    # itself ("agentrunrole"), one by the naming convention
    # ("ck_agent_runs_agentrunrole"). Altering the column without dropping
    # both first preserves the OLD (3-value) one verbatim alongside a NEW
    # one, so the OLD constraint silently keeps rejecting 'evaluator' even
    # though the new constraint allows it (SQLite enforces every CHECK on
    # a table). Verified empirically against a disposable test DB.
    # Dropping is done conditionally (checked names actually present)
    # rather than unconditionally, so this migration applies cleanly both
    # to a database still carrying that historical duplicate and to one
    # where a prior downgrade of this same migration already cleaned it
    # up (downgrade converges to a single, correctly-named constraint and
    # stays that way).
    bind = op.get_bind()
    existing_role_check_names = {c["name"] for c in sa.inspect(bind).get_check_constraints("agent_runs")}

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        if "agentrunrole" in existing_role_check_names:
            batch_op.drop_constraint(batch_op.f("agentrunrole"), type_="check")
        if "ck_agent_runs_agentrunrole" in existing_role_check_names:
            batch_op.drop_constraint(batch_op.f("ck_agent_runs_agentrunrole"), type_="check")
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum(
                "primary",
                "reviewer",
                "repair",
                "evaluator",
                name="agentrunrole",
                native_enum=False,
                create_constraint=True,
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("evaluation_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("evaluator_agent_version_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("evaluator_model_policy_override_json", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("evaluator_task_run_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("evaluator_agent_run_id", sa.String(length=36), nullable=True))
        batch_op.alter_column(
            "method",
            existing_type=sa.VARCHAR(length=13),
            type_=sa.Enum(
                "deterministic",
                "agent_evaluator",
                name="evaluationmethod",
                native_enum=False,
                create_constraint=True,
            ),
            existing_nullable=False,
        )
        # Autogenerate misses this one: 'completed' and 'cancelled' are
        # both 9 characters, so the rendered VARCHAR length is unchanged
        # and its type-comparator sees no diff -- but the CHECK
        # constraint's allowed-values list still needs 'cancelled' added,
        # or inserting/updating an EvaluationRun to CANCELLED would raise
        # an IntegrityError. Verified empirically against a disposable
        # test DB before adding this by hand.
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=9),
            type_=sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="evaluationrunstatus",
                native_enum=False,
                create_constraint=True,
            ),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_evaluation_runs_evaluator_agent_run_id"), ["evaluator_agent_run_id"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_evaluation_runs_evaluator_task_run_id"), ["evaluator_task_run_id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluation_runs_evaluator_agent_run_id_agent_runs"),
            "agent_runs",
            ["evaluator_agent_run_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluation_runs_evaluator_agent_version_id_agent_versions"),
            "agent_versions",
            ["evaluator_agent_version_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluation_runs_evaluator_task_run_id_task_runs"),
            "task_runs",
            ["evaluator_task_run_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluation_runs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_evaluation_runs_evaluator_task_run_id_task_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_evaluation_runs_evaluator_agent_version_id_agent_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_evaluation_runs_evaluator_agent_run_id_agent_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("uq_evaluation_runs_evaluator_task_run_id"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_evaluation_runs_evaluator_agent_run_id"), type_="unique")
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="evaluationrunstatus",
                native_enum=False,
                create_constraint=True,
            ),
            type_=sa.VARCHAR(length=9),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "method",
            existing_type=sa.Enum(
                "deterministic",
                "agent_evaluator",
                name="evaluationmethod",
                native_enum=False,
                create_constraint=True,
            ),
            type_=sa.VARCHAR(length=13),
            existing_nullable=False,
        )
        batch_op.drop_column("evaluator_agent_run_id")
        batch_op.drop_column("evaluator_task_run_id")
        batch_op.drop_column("evaluator_model_policy_override_json")
        batch_op.drop_column("evaluator_agent_version_id")

    bind = op.get_bind()
    existing_role_check_names = {c["name"] for c in sa.inspect(bind).get_check_constraints("agent_runs")}

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        # Symmetric with upgrade()'s conditional drop above -- only ever
        # one constraint is present at this point (upgrade() always
        # converges to "ck_agent_runs_agentrunrole" alone), but checking
        # rather than assuming keeps this migration safe to re-run in
        # either direction from either historical starting state. This
        # converges agent_runs.role to a single, correctly-named
        # constraint going forward -- e0b0be06e2c5 (MA4)'s own downgrade()
        # was made tolerant of that (checks before dropping) for exactly
        # this reason, so a full base-to-head-to-base chain still works.
        if "agentrunrole" in existing_role_check_names:
            batch_op.drop_constraint(batch_op.f("agentrunrole"), type_="check")
        if "ck_agent_runs_agentrunrole" in existing_role_check_names:
            batch_op.drop_constraint(batch_op.f("ck_agent_runs_agentrunrole"), type_="check")
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum(
                "primary",
                "reviewer",
                "repair",
                "evaluator",
                name="agentrunrole",
                native_enum=False,
                create_constraint=True,
            ),
            type_=sa.Enum(
                "primary",
                "reviewer",
                "repair",
                name="agentrunrole",
                native_enum=False,
                create_constraint=True,
            ),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
