"""ma4 add agent review contract

Revision ID: e0b0be06e2c5
Revises: 60d932811e9b
Create Date: 2026-09-16 20:53:18.016368

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b0be06e2c5"
down_revision: Union[str, None] = "60d932811e9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_reviews",
        sa.Column("task_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("reviewer_agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_agent_version_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_provider_model_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("iteration_number", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "accept",
                "repair_required",
                "invalid",
                name="reviewdecision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("issues_json", sa.JSON(), nullable=True),
        sa.Column("repair_instructions", sa.Text(), nullable=True),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_reviews_candidate_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_agent_reviews_candidate_artifact_id_artifacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_reviews_reviewer_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_reviews_reviewer_agent_version_id_agent_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_provider_model_snapshot_id"],
            ["provider_model_snapshots.id"],
            name=op.f("fk_agent_reviews_reviewer_provider_model_snapshot_id_provider_model_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["task_runs.id"],
            name=op.f("fk_agent_reviews_task_run_id_task_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_reviews")),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role",
                sa.Enum(
                    "primary",
                    "reviewer",
                    "repair",
                    name="agentrunrole",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("repair_of_review_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("input_context_json", sa.JSON(), nullable=True))
        batch_op.create_foreign_key(
            "fk_agent_runs_repair_of_review_id_agent_reviews",
            "agent_reviews",
            ["repair_of_review_id"],
            ["id"],
            ondelete="SET NULL",
            use_alter=True,
        )

    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("final_artifact_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_task_runs_final_artifact_id_artifacts",
            "artifacts",
            ["final_artifact_id"],
            ["id"],
            use_alter=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_task_runs_final_artifact_id_artifacts", type_="foreignkey")
        batch_op.drop_column("final_artifact_id")

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_agent_runs_repair_of_review_id_agent_reviews", type_="foreignkey")
        # SQLite batch-mode add_column on an Enum(create_constraint=True)
        # column (added by this same migration's upgrade()) leaves *two*
        # physical CHECK constraints behind -- one auto-named by the Enum
        # type itself ("agentrunrole"), one by the naming convention
        # ("ck_agent_runs_agentrunrole") -- both must be dropped before
        # the column, or SQLite's table-recreate fails with "no such
        # column: role" trying to keep a CHECK on a column being removed.
        batch_op.drop_constraint(batch_op.f("agentrunrole"), type_="check")
        batch_op.drop_constraint(batch_op.f("ck_agent_runs_agentrunrole"), type_="check")
        batch_op.drop_column("input_context_json")
        batch_op.drop_column("repair_of_review_id")
        batch_op.drop_column("role")

    op.drop_table("agent_reviews")
    # ### end Alembic commands ###
