"""ail1a learning foundation

Revision ID: ef873dac62a1
Revises: 8c3f6b2e9d14
Create Date: 2026-09-22 17:52:23.165637

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef873dac62a1"
down_revision: Union[str, None] = "8c3f6b2e9d14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("aliases_json", sa.JSON(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "foundational",
                "practitioner",
                "advanced",
                name="conceptlevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "definitional",
                "mechanism",
                "operational",
                "architectural",
                name="conceptkind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.Column("freshness_days", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "deprecated",
                "retired",
                name="versionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concepts")),
        sa.UniqueConstraint("slug", name=op.f("uq_concepts_slug")),
    )
    op.create_table(
        "taxonomy_terms",
        sa.Column("vocabulary", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("ma_phase", sa.String(length=10), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["taxonomy_terms.id"], name=op.f("fk_taxonomy_terms_parent_id_taxonomy_terms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_terms")),
        sa.UniqueConstraint("vocabulary", "key", name="uq_taxonomy_terms_vocabulary_key"),
    )
    with op.batch_alter_table("taxonomy_terms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_taxonomy_terms_vocabulary"), ["vocabulary"], unique=False)

    op.create_table(
        "concept_relations",
        sa.Column("from_concept_id", sa.String(length=36), nullable=False),
        sa.Column("to_concept_id", sa.String(length=36), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "prerequisite",
                "part_of",
                "related",
                name="conceptrelationtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_concept_id"],
            ["concepts.id"],
            name=op.f("fk_concept_relations_from_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_concept_id"],
            ["concepts.id"],
            name=op.f("fk_concept_relations_to_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_relations")),
        sa.UniqueConstraint(
            "from_concept_id", "to_concept_id", "relation_type", name="uq_concept_relations_from_to_type"
        ),
    )
    op.create_table(
        "concept_terms",
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_concept_terms_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["taxonomy_terms.id"],
            name=op.f("fk_concept_terms_term_id_taxonomy_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_terms")),
        sa.UniqueConstraint("concept_id", "term_id", name="uq_concept_terms_concept_id_term_id"),
    )
    op.create_table(
        "concept_versions",
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("plain_definition", sa.Text(), nullable=False),
        sa.Column("technical_explanation", sa.Text(), nullable=True),
        sa.Column("examples_md", sa.Text(), nullable=True),
        sa.Column("evidence_requirements_json", sa.JSON(), nullable=True),
        sa.Column(
            "content_origin",
            sa.Enum(
                "human",
                "ai_drafted_reviewed",
                "ai_drafted_unreviewed",
                name="contentorigin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column(
            "change_severity",
            sa.Enum("minor", "material", name="changeseverity", native_enum=False, create_constraint=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "deprecated",
                "retired",
                name="versionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_concept_versions_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_versions")),
        sa.UniqueConstraint("concept_id", "version", name="uq_concept_versions_concept_id_version"),
    )
    op.create_table(
        "learning_items",
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "resource",
                "exercise",
                "check_question",
                "scenario",
                "lab",
                "observation_task",
                name="learningitemtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=True),
        sa.Column("spec_json", sa.JSON(), nullable=True),
        sa.Column(
            "grading_mode",
            sa.Enum(
                "deterministic",
                "ai_rubric",
                "human",
                "self",
                name="gradingmode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("est_minutes", sa.Integer(), nullable=True),
        sa.Column("requires_capability_term_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_learning_items_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requires_capability_term_id"],
            ["taxonomy_terms.id"],
            name=op.f("fk_learning_items_requires_capability_term_id_taxonomy_terms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_items")),
    )
    op.create_table(
        "learner_interests",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=True),
        sa.Column("concept_id", sa.String(length=36), nullable=True),
        sa.Column("watch", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_learner_interests_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["taxonomy_terms.id"],
            name=op.f("fk_learner_interests_term_id_taxonomy_terms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_interests_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_interests")),
    )
    with op.batch_alter_table("learner_interests", schema=None) as batch_op:
        batch_op.create_index(
            "uq_learner_interests_user_id_concept_id",
            ["user_id", "concept_id"],
            unique=True,
            sqlite_where=sa.text("concept_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_learner_interests_user_id_term_id",
            ["user_id", "term_id"],
            unique=True,
            sqlite_where=sa.text("term_id IS NOT NULL"),
        )

    op.create_table(
        "learner_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "foundational",
                "practitioner",
                "advanced",
                name="conceptlevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("goal_text", sa.Text(), nullable=True),
        sa.Column(
            "depth",
            sa.Enum(
                "survey", "working", "deep", name="learnerdepth", native_enum=False, create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("weekly_minutes", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_learner_profiles_user_id")),
    )
    op.create_table(
        "learning_evidence",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("concept_version_id", sa.String(length=36), nullable=False),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "lesson_completed",
                "knowledge_check",
                "observation",
                "lab",
                "interpretation",
                "self_report",
                name="evidencetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("learning_item_id", sa.String(length=36), nullable=True),
        sa.Column("score_json", sa.JSON(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column(
            "grader",
            sa.Enum(
                "deterministic",
                "ai_rubric",
                "human",
                "self",
                name="gradingmode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("grader_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "question_origin",
            sa.Enum(
                "reviewed", "generated", name="questionorigin", native_enum=False, create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("on_demo_data", sa.Boolean(), nullable=False),
        sa.Column(
            "ref_type",
            sa.Enum(
                "agent_run",
                "evaluation_run",
                "model_routing_decision",
                "tool_call",
                "workflow_run",
                "human",
                "none",
                name="evidencereftype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.String(length=36), nullable=True),
        sa.Column("superseded_by_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_learning_evidence_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["concept_version_id"],
            ["concept_versions.id"],
            name=op.f("fk_learning_evidence_concept_version_id_concept_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_learning_evidence_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["learning_evidence.id"],
            name=op.f("fk_learning_evidence_superseded_by_id_learning_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_evidence_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_evidence")),
    )
    op.create_table(
        "learning_plan_items",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "proposed",
                "planned",
                "skipped",
                "done",
                "rejected",
                name="planitemstate",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "planner",
                "user",
                "professor",
                name="planitemorigin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_learning_plan_items_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_plan_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_plan_items")),
    )
    with op.batch_alter_table("learning_plan_items", schema=None) as batch_op:
        batch_op.create_index(
            "uq_learning_plan_items_user_id_concept_id_active",
            ["user_id", "concept_id"],
            unique=True,
            sqlite_where=sa.text("state IN ('proposed', 'planned')"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learning_plan_items", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_learning_plan_items_user_id_concept_id_active",
            sqlite_where=sa.text("state IN ('proposed', 'planned')"),
        )

    op.drop_table("learning_plan_items")
    op.drop_table("learning_evidence")
    op.drop_table("learner_profiles")
    with op.batch_alter_table("learner_interests", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_learner_interests_user_id_term_id", sqlite_where=sa.text("term_id IS NOT NULL")
        )
        batch_op.drop_index(
            "uq_learner_interests_user_id_concept_id", sqlite_where=sa.text("concept_id IS NOT NULL")
        )

    op.drop_table("learner_interests")
    op.drop_table("learning_items")
    op.drop_table("concept_versions")
    op.drop_table("concept_terms")
    op.drop_table("concept_relations")
    with op.batch_alter_table("taxonomy_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_taxonomy_terms_vocabulary"))

    op.drop_table("taxonomy_terms")
    op.drop_table("concepts")
    # ### end Alembic commands ###
