"""ma0 initial schema

Revision ID: f85ec3fb33ae
Revises: 
Create Date: 2026-09-16 14:05:01.674761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85ec3fb33ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('api_request', 'tool_call', name='idempotencyscope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('result_ref_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', name='idempotencystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('key', name=op.f('uq_idempotency_keys_key'))
    )
    op.create_table('job_queue',
    sa.Column('job_type', sa.Enum('agent_run', 'workflow_node', 'evaluation', name='jobtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('payload_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'leased', 'done', 'failed', name='jobqueuestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_queue')),
    sa.UniqueConstraint('job_type', 'payload_ref', name='uq_job_queue_job_type_payload_ref')
    )
    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_queue_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_queue_status'), ['status'], unique=False)

    op.create_table('models',
    sa.Column('canonical_model_id', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('input_modalities_json', sa.JSON(), nullable=True),
    sa.Column('output_modalities_json', sa.JSON(), nullable=True),
    sa.Column('tool_calling_support', sa.Enum('none', 'basic', 'parallel', 'structured', name='toolcallingsupport', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('structured_output_support', sa.Boolean(), nullable=False),
    sa.Column('reasoning_tier', sa.String(length=40), nullable=True),
    sa.Column('coding_capability_tier', sa.String(length=40), nullable=True),
    sa.Column('vision_capability', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deprecated', 'unavailable', name='modelstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('canonical_model_id', name=op.f('uq_models_canonical_model_id'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('policy_rules',
    sa.Column('scope', sa.Enum('global', 'project', 'agent_version', 'tool', name='policyrulescope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rule_type', sa.Enum('approval_required', 'tool_allow', 'tool_deny', name='policyruletype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_ref', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rules'))
    )
    op.create_table('providers',
    sa.Column('type', sa.Enum('openrouter', 'direct', 'local', 'enterprise', name='providertype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('health_status', sa.Enum('up', 'degraded', 'down', name='healthstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_table('router_policy_versions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scoring_config_json', sa.JSON(), nullable=True),
    sa.Column('free_policy', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_router_policy_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_router_policy_versions_version'))
    )
    op.create_table('tools',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema_ref', sa.String(length=500), nullable=True),
    sa.Column('tool_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'deprecated', name='toolstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    op.create_table('model_capabilities',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('capability_key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_capabilities_model_id_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_capabilities')),
    sa.UniqueConstraint('model_id', 'capability_key', name='uq_model_capabilities_model_id_key')
    )
    op.create_table('projects',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_settings_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_projects_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('provider_models',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('provider_model_id', sa.String(length=255), nullable=False),
    sa.Column('cost_input_per_mtok', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cost_output_per_mtok', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('latency_p50_ms', sa.Integer(), nullable=True),
    sa.Column('throughput_tokens_per_sec', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('availability_status', sa.Enum('up', 'degraded', 'down', name='healthstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('privacy_characteristics_json', sa.JSON(), nullable=True),
    sa.Column('supported_features_json', sa.JSON(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('cost_input_per_mtok IS NULL OR cost_input_per_mtok >= 0', name=op.f('ck_provider_models_cost_input_nonneg')),
    sa.CheckConstraint('cost_output_per_mtok IS NULL OR cost_output_per_mtok >= 0', name=op.f('ck_provider_models_cost_output_nonneg')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_provider_models_model_id_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_models_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_models')),
    sa.UniqueConstraint('model_id', 'provider_id', name='uq_provider_models_model_id_provider_id')
    )
    op.create_table('users',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='orgrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('org_id', 'email', name='uq_users_org_id_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('agents',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_status', sa.Enum('draft', 'active', 'deprecated', 'retired', name='versionstatus', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_table('audit_events',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('target_ref', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_events_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('budgets',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.Enum('execution', 'task', 'user', 'project', 'day', 'month', name='budgetscope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope_ref_id', sa.String(length=36), nullable=True),
    sa.Column('limit_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('threshold_warn_pct', sa.Integer(), nullable=False),
    sa.Column('threshold_critical_pct', sa.Integer(), nullable=False),
    sa.Column('threshold_hard_pct', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_budgets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_table('project_memberships',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='projectrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_project_memberships_granted_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_memberships_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_memberships')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_memberships_project_id_user_id')
    )
    op.create_table('provider_model_snapshots',
    sa.Column('provider_model_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('pricing_input_per_mtok', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pricing_output_per_mtok', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('capability_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_provider_model_snapshots_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_model_snapshots_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], name=op.f('fk_provider_model_snapshots_provider_model_id_provider_models'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_model_snapshots'))
    )
    op.create_table('secret_references',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('secret_store_ref', sa.String(length=500), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_secret_references_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_secret_references_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_secret_references_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_references'))
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements_json', sa.JSON(), nullable=True),
    sa.Column('execution_mode', sa.Enum('single_agent', 'build_review', 'parallel_comparison', 'workflow', name='executionmode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'archived', name='taskstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('usage_events',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('model_call', 'tool_call', name='usagesourcetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_ref_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_usage_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_table('workflows',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.Enum('draft', 'active', 'deprecated', 'retired', name='versionstatus', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflows_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_table('prompt_versions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_prompt_versions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_prompt_versions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('agent_id', 'version', name='uq_prompt_versions_agent_id_version')
    )
    op.create_table('usage_event_budgets',
    sa.Column('usage_event_id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_usage_event_budgets_budget_id_budgets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], name=op.f('fk_usage_event_budgets_usage_event_id_usage_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_event_budgets')),
    sa.UniqueConstraint('usage_event_id', 'budget_id', name='uq_usage_event_budgets_event_id_budget_id')
    )
    op.create_table('workflow_versions',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'deprecated', 'retired', name='versionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_versions_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_versions')),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_versions_workflow_id_version')
    )
    op.create_table('agent_versions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=True),
    sa.Column('model_policy_json', sa.JSON(), nullable=True),
    sa.Column('default_model_strategy', sa.Enum('manual_required', 'auto_preferred', 'auto_with_manual_override', name='defaultmodelstrategy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('context_policy_json', sa.JSON(), nullable=True),
    sa.Column('memory_policy_json', sa.JSON(), nullable=True),
    sa.Column('budget_policy_json', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_policy_json', sa.JSON(), nullable=True),
    sa.Column('approval_requirements_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'deprecated', 'retired', name='versionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_versions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_agent_versions_prompt_version_id_prompt_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_versions_agent_id_version')
    )
    op.create_table('task_runs',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'waiting_for_agent', 'waiting_for_tool', 'waiting_for_approval', 'verifying', 'cancelling', 'cancelled', 'completed', 'failed', name='taskrunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=True),
    sa.Column('config_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_task_runs_budget_id_budgets')),
    sa.ForeignKeyConstraint(['cancellation_requested_by'], ['users.id'], name=op.f('fk_task_runs_cancellation_requested_by_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_runs_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_task_runs_workflow_version_id_workflow_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs'))
    )
    op.create_table('workflow_nodes',
    sa.Column('workflow_version_id', sa.String(length=36), nullable=False),
    sa.Column('node_key', sa.String(length=120), nullable=False),
    sa.Column('node_type', sa.Enum('agent', 'parallel_group', 'conditional', 'repair_loop', 'judge', 'consensus', 'human_approval', 'terminal', name='workflownodetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("node_type != 'repair_loop' OR max_iterations IS NOT NULL", name=op.f('ck_workflow_nodes_repair_loop_requires_max_iterations')),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_nodes_workflow_version_id_workflow_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_nodes')),
    sa.UniqueConstraint('workflow_version_id', 'node_key', name='uq_workflow_nodes_version_id_node_key')
    )
    op.create_table('agent_runs',
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_version_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('provider_model_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('created', 'sandbox_provisioning', 'running', 'waiting_for_tool', 'waiting_for_model', 'cancelling', 'stopped', 'completed', 'failed', name='agentrunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sandbox_ref', sa.String(length=500), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_by', sa.String(length=36), nullable=True),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_agent_runs_agent_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['cancellation_requested_by'], ['users.id'], name=op.f('fk_agent_runs_cancellation_requested_by_users')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_agent_runs_model_id_models')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_agent_runs_provider_id_providers')),
    sa.ForeignKeyConstraint(['provider_model_snapshot_id'], ['provider_model_snapshots.id'], name=op.f('fk_agent_runs_provider_model_snapshot_id_provider_model_snapshots')),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_agent_runs_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_table('agent_version_tool_grants',
    sa.Column('agent_version_id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('grant_type', sa.Enum('allow', 'deny', name='toolgranttype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_agent_version_tool_grants_agent_version_id_agent_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_agent_version_tool_grants_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_version_tool_grants')),
    sa.UniqueConstraint('agent_version_id', 'tool_id', 'grant_type', name='uq_agent_version_tool_grants_version_tool_type')
    )
    op.create_table('source_snapshots',
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('repo_url_or_path', sa.String(length=1000), nullable=False),
    sa.Column('base_ref', sa.String(length=255), nullable=False),
    sa.Column('base_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('working_branch_name', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_source_snapshots_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots')),
    sa.UniqueConstraint('task_run_id', name=op.f('uq_source_snapshots_task_run_id'))
    )
    op.create_table('workflow_edges',
    sa.Column('workflow_version_id', sa.String(length=36), nullable=False),
    sa.Column('from_node_id', sa.String(length=36), nullable=False),
    sa.Column('to_node_id', sa.String(length=36), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_from_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_to_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_edges_workflow_version_id_workflow_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_edges'))
    )
    op.create_table('workflow_runs',
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'node_waiting_for_agent', 'node_waiting_for_approval', 'repair_loop_active', 'escalated', 'cancelling', 'cancelled', 'completed', 'failed', name='workflowrunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cancellation_requested_by'], ['users.id'], name=op.f('fk_workflow_runs_cancellation_requested_by_users')),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_workflow_runs_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_runs_workflow_version_id_workflow_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs')),
    sa.UniqueConstraint('task_run_id', name=op.f('uq_workflow_runs_task_run_id'))
    )
    op.create_table('agent_run_attempts',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='agentrunattemptstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_run_attempts_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run_attempts')),
    sa.UniqueConstraint('agent_run_id', 'attempt_number', name='uq_agent_run_attempts_run_id_attempt_number')
    )
    op.create_table('artifacts',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('diff', 'file', 'report', 'log', name='artifacttype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_ref', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_artifacts_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_table('budget_reservations',
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('task_run_id', sa.String(length=36), nullable=True),
    sa.Column('reserved_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.Enum('active', 'committed', 'released', name='budgetreservationstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_budget_reservations_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_reservations_budget_id_budgets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_budget_reservations_task_run_id_task_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_reservations'))
    )
    op.create_table('comparison_runs',
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='comparisonrunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('winner_agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_comparison_runs_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_agent_run_id'], ['agent_runs.id'], name=op.f('fk_comparison_runs_winner_agent_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparison_runs'))
    )
    op.create_table('evaluations',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('objective_metrics_json', sa.JSON(), nullable=True),
    sa.Column('metric_provenance_json', sa.JSON(), nullable=True),
    sa.Column('judge_score_json', sa.JSON(), nullable=True),
    sa.Column('judge_source', sa.Enum('llm_judge', name='evaluationjudgesource', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('human_decision', sa.Enum('accepted', 'rejected', name='evaluationhumandecision', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_evaluations_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('agent_run_id', name=op.f('uq_evaluations_agent_run_id'))
    )
    op.create_table('model_routing_decisions',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('router_policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('selection_mode', sa.Enum('manual', 'auto', name='modelselectionmode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('eligible_candidates_json', sa.JSON(), nullable=True),
    sa.Column('selected_provider_model_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_model_routing_decisions_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['router_policy_version_id'], ['router_policy_versions.id'], name=op.f('fk_model_routing_decisions_router_policy_version_id_router_policy_versions')),
    sa.ForeignKeyConstraint(['selected_provider_model_snapshot_id'], ['provider_model_snapshots.id'], name=op.f('fk_model_routing_decisions_selected_provider_model_snapshot_id_provider_model_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_routing_decisions'))
    )
    op.create_table('workflow_node_runs',
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_node_id', sa.String(length=36), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'waiting_for_approval', 'completed', 'failed', 'cancelled', name='workflownoderunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_snapshot_ref', sa.String(length=1000), nullable=True),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_workflow_node_runs_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_node_runs_workflow_node_id_workflow_nodes')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_node_runs_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_node_runs')),
    sa.UniqueConstraint('workflow_run_id', 'workflow_node_id', 'iteration', name='uq_workflow_node_runs_run_node_iteration')
    )
    op.create_table('approvals',
    sa.Column('scope', sa.Enum('task_run', 'agent_run', 'workflow_node_run', 'artifact', name='approvalscope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope_ref_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=120), nullable=False),
    sa.Column('policy_rule_id', sa.String(length=36), nullable=True),
    sa.Column('action_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('bound_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='approvalstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bound_artifact_id'], ['artifacts.id'], name=op.f('fk_approvals_bound_artifact_id_artifacts')),
    sa.ForeignKeyConstraint(['policy_rule_id'], ['policy_rules.id'], name=op.f('fk_approvals_policy_rule_id_policy_rules')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approvals_requested_by_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_approvals_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_table('comparison_candidates',
    sa.Column('comparison_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_comparison_candidates_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comparison_run_id'], ['comparison_runs.id'], name=op.f('fk_comparison_candidates_comparison_run_id_comparison_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparison_candidates')),
    sa.UniqueConstraint('comparison_run_id', 'agent_run_id', name='uq_comparison_candidates_run_id_agent_run_id'),
    sa.UniqueConstraint('comparison_run_id', 'label', name='uq_comparison_candidates_run_id_label')
    )
    op.create_table('model_calls',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('provider_model_id', sa.String(length=36), nullable=True),
    sa.Column('provider_model_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('model_routing_decision_id', sa.String(length=36), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cost_currency', sa.String(length=10), nullable=False),
    sa.Column('cost_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('structured_output_ok', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'error', 'timeout', name='modelcallstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_attempt_id'], ['agent_run_attempts.id'], name=op.f('fk_model_calls_agent_run_attempt_id_agent_run_attempts')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_model_calls_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_calls_model_id_models')),
    sa.ForeignKeyConstraint(['model_routing_decision_id'], ['model_routing_decisions.id'], name=op.f('fk_model_calls_model_routing_decision_id_model_routing_decisions')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_model_calls_provider_id_providers')),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], name=op.f('fk_model_calls_provider_model_id_provider_models')),
    sa.ForeignKeyConstraint(['provider_model_snapshot_id'], ['provider_model_snapshots.id'], name=op.f('fk_model_calls_provider_model_snapshot_id_provider_model_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_calls'))
    )
    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key_id', sa.String(length=36), nullable=True),
    sa.Column('inputs_ref', sa.String(length=1000), nullable=True),
    sa.Column('outputs_ref', sa.String(length=1000), nullable=True),
    sa.Column('permission_decision', sa.Enum('allowed', 'denied', name='permissiondecision', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'denied', name='toolcallstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_attempt_id'], ['agent_run_attempts.id'], name=op.f('fk_tool_calls_agent_run_attempt_id_agent_run_attempts')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_tool_calls_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idempotency_key_id'], ['idempotency_keys.id'], name=op.f('fk_tool_calls_idempotency_key_id_idempotency_keys')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_calls_tool_id_tools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_table('execution_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_node_run_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('agent_version_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('artifact_refs_json', sa.JSON(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('redaction_policy_version', sa.String(length=40), nullable=True),
    sa.Column('redacted_fields_json', sa.JSON(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_execution_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_execution_events_agent_id_agents')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_execution_events_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_execution_events_agent_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_execution_events_model_id_models')),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_execution_events_prompt_version_id_prompt_versions')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_execution_events_provider_id_providers')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_execution_events_task_id_tasks')),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_execution_events_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], name=op.f('fk_execution_events_tool_call_id_tool_calls')),
    sa.ForeignKeyConstraint(['workflow_node_run_id'], ['workflow_node_runs.id'], name=op.f('fk_execution_events_workflow_node_run_id_workflow_node_runs')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_execution_events_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events')),
    sa.UniqueConstraint('task_run_id', 'sequence_number', name='uq_execution_events_task_run_id_sequence_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_events')
    op.drop_table('tool_calls')
    op.drop_table('model_calls')
    op.drop_table('comparison_candidates')
    op.drop_table('approvals')
    op.drop_table('workflow_node_runs')
    op.drop_table('model_routing_decisions')
    op.drop_table('evaluations')
    op.drop_table('comparison_runs')
    op.drop_table('budget_reservations')
    op.drop_table('artifacts')
    op.drop_table('agent_run_attempts')
    op.drop_table('workflow_runs')
    op.drop_table('workflow_edges')
    op.drop_table('source_snapshots')
    op.drop_table('agent_version_tool_grants')
    op.drop_table('agent_runs')
    op.drop_table('workflow_nodes')
    op.drop_table('task_runs')
    op.drop_table('agent_versions')
    op.drop_table('workflow_versions')
    op.drop_table('usage_event_budgets')
    op.drop_table('prompt_versions')
    op.drop_table('workflows')
    op.drop_table('usage_events')
    op.drop_table('tasks')
    op.drop_table('secret_references')
    op.drop_table('provider_model_snapshots')
    op.drop_table('project_memberships')
    op.drop_table('budgets')
    op.drop_table('audit_events')
    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('provider_models')
    op.drop_table('projects')
    op.drop_table('model_capabilities')
    op.drop_table('tools')
    op.drop_table('router_policy_versions')
    op.drop_table('providers')
    op.drop_table('policy_rules')
    op.drop_table('organizations')
    op.drop_table('models')
    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_queue_status'))
        batch_op.drop_index(batch_op.f('ix_job_queue_lease_expires_at'))

    op.drop_table('job_queue')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
