"""AIL.5C Grader golden-set release gate (design section I, "Release gate").

    Before a Grader version or model policy becomes ACTIVE, an offline golden-set
    run confirms expected findings on authored responses per definition
    (2 clear pass, 2 clear fail, 2 borderline). This is a test and script gate,
    not a schema.

The gate runs a *candidate* Grader configuration (an Agent Version's prompt and
model policy, or a pinned provider model) through the real machinery: the
allowlisted ``GradingPacketBuilder``, the ``Academy Grader`` with its
``grading_contract_v1`` parsing and its cross-check. It only replaces the
learner: each golden response is frozen into a synthetic attempt of the real
definition, with the deterministic stage assumed met, so that what is measured
is the Grader's judgment and nothing else. It writes no evidence and derives no
state, and it must only ever be run against a disposable database (the CLI
enforces that by working on a copy).

A candidate is **release-ready** only if every case of every approved
definition matches its expectation and every approved definition is covered.
Anything less is *not ready*; there is no partial pass.

Golden cases are authored per definition. Where none are authored, they are
derived deterministically from the definition's own authored reference points
(never generated by a model), and marked ``derived_from_reference_points``.
"""

import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.assessment_contract import GRADING_CONTRACT_VERSION, sha256_hex
from app.assessment_outcome import GRADING_COMPLETE
from app.db.enums import (
    AssessmentAttemptStatus,
    AssessmentDefinitionStatus,
    AssessmentOrigin,
    AssessmentResultKind,
)
from app.models.agents import AgentVersion, PromptVersion
from app.models.assessment import AssessmentAttempt, AssessmentDefinition, AssessmentResult
from app.models.identity import User
from app.services.assessment_challenge_service import draw_challenge
from app.services.assessment_grader_service import AssessmentGraderService
from app.services.assessment_service import AssessmentService

GOLDEN_SET_VERSION = "golden_set_v1"
CLEAR_PASS, CLEAR_FAIL, BORDERLINE = "clear_pass", "clear_fail", "borderline"
REQUIRED_SHAPE = {CLEAR_PASS: 2, CLEAR_FAIL: 2, BORDERLINE: 2}
ORIGIN_AUTHORED = "authored"
ORIGIN_DERIVED = "derived_from_reference_points"

# Authored golden cases, keyed by definition_key. Each case:
#   {"case_id": str, "klass": CLEAR_PASS|CLEAR_FAIL|BORDERLINE, "response": str,
#    "absent_criteria": [criterion keys whose ideas the response wholly omits]}
# A definition without an entry here gets the derived set (see ``golden_cases``).
AUTHORED_GOLDEN: Dict[str, List[Dict[str, Any]]] = {}

# Two answers that address none of the authored points, however a criterion is worded.
_OFF_TOPIC = (
    (
        "I think this is a big topic and there are many opinions about it. It really depends on many "
        "things, and people say all kinds of different stuff, so I am not sure what to say here."
    ),
    (
        "Honestly I have not studied this yet. My answer is that it is interesting and important, "
        "and I like learning new things every day."
    ),
)


class GoldenSetIncomplete(ValueError):
    """A definition cannot be gated: its golden set is missing or malformed."""


@dataclass(frozen=True)
class GoldenCase:
    definition_key: str
    case_id: str
    klass: str
    response: str
    absent_criteria: tuple = ()
    origin: str = ORIGIN_DERIVED


@dataclass
class CaseResult:
    definition_key: str
    case_id: str
    klass: str
    origin: str
    passed: bool
    reasons: List[str] = field(default_factory=list)
    grading_status: str = ""
    findings: Dict[str, List[str]] = field(default_factory=dict)  # criterion -> finding per run
    models: List[Optional[str]] = field(default_factory=list)


@dataclass
class GoldenGateReport:
    golden_set_version: str
    grading_contract_version: str
    candidate: Dict[str, Any]
    coverage: Dict[str, List[str]]
    definitions: Dict[str, Dict[str, Any]]
    cases: List[CaseResult]
    release_ready: bool
    reasons: List[str]

    def to_json(self) -> Dict[str, Any]:
        body = {
            "golden_set_version": self.golden_set_version,
            "grading_contract_version": self.grading_contract_version,
            "candidate": self.candidate,
            "coverage": self.coverage,
            "definitions": self.definitions,
            "cases": [c.__dict__ for c in self.cases],
            "release_ready": self.release_ready,
            "reasons": self.reasons,
        }
        return {**body, "report_hash": sha256_hex(body)}


# -- the golden set -------------------------------------------------------------------------------------------


def _judged(definition: AssessmentDefinition) -> List[dict]:
    return [c for c in definition.criteria if c["method"] == "grader"]


def golden_cases(
    definition: AssessmentDefinition, authored: Optional[Dict[str, List[Dict[str, Any]]]] = None
) -> List[GoldenCase]:
    """The 2 / 2 / 2 golden set for one definition (authored, else derived), validated."""
    key = definition.definition_key
    source = AUTHORED_GOLDEN if authored is None else authored
    if key in source:
        cases = [
            GoldenCase(
                definition_key=key,
                case_id=c["case_id"],
                klass=c["klass"],
                response=c["response"],
                absent_criteria=tuple(c.get("absent_criteria") or ()),
                origin=ORIGIN_AUTHORED,
            )
            for c in source[key]
        ]
    else:
        cases = _derive(definition)
    validate_golden_set(definition, cases)
    return cases


def _derive(definition: AssessmentDefinition) -> List[GoldenCase]:
    points: List[tuple] = [
        (c["key"], p) for c in _judged(definition) for p in (c.get("reference_points") or [])
    ]
    if len(points) < 2:
        raise GoldenSetIncomplete(
            f"{definition.definition_key}: at least two authored reference points are needed to derive "
            "borderline cases; author the golden cases for this definition"
        )
    half = (len(points) + 1) // 2
    first, second = points[:half], points[half:]

    def text(items) -> str:
        return " ".join(p for _k, p in items)

    def absent(kept) -> tuple:
        present = {k for k, _p in kept}
        return tuple(c["key"] for c in _judged(definition) if c["key"] not in present)

    key = definition.definition_key
    return [
        GoldenCase(key, "pass-1", CLEAR_PASS, text(points)),
        GoldenCase(key, "pass-2", CLEAR_PASS, "To put it another way: " + text(list(reversed(points)))),
        GoldenCase(key, "fail-1", CLEAR_FAIL, _OFF_TOPIC[0]),
        GoldenCase(key, "fail-2", CLEAR_FAIL, _OFF_TOPIC[1]),
        GoldenCase(key, "borderline-1", BORDERLINE, text(first), absent_criteria=absent(first)),
        GoldenCase(key, "borderline-2", BORDERLINE, text(second), absent_criteria=absent(second)),
    ]


def validate_golden_set(definition: AssessmentDefinition, cases: Sequence[GoldenCase]) -> None:
    key = definition.definition_key
    judged_keys = {c["key"] for c in _judged(definition)}
    if not judged_keys:
        raise GoldenSetIncomplete(f"{key}: has no Grader-judged criteria, so there is nothing to gate")
    shape = {klass: sum(1 for c in cases if c.klass == klass) for klass in REQUIRED_SHAPE}
    if shape != REQUIRED_SHAPE:
        raise GoldenSetIncomplete(
            f"{key}: a golden set needs 2 clear pass, 2 clear fail and 2 borderline cases; has {shape}"
        )
    if len({c.case_id for c in cases}) != len(cases):
        raise GoldenSetIncomplete(f"{key}: golden case ids must be unique")
    if len({c.response for c in cases}) != len(cases):
        raise GoldenSetIncomplete(f"{key}: golden responses must be distinct")
    for case in cases:
        if not case.response.strip():
            raise GoldenSetIncomplete(f"{key}/{case.case_id}: empty golden response")
        if not set(case.absent_criteria) <= judged_keys:
            raise GoldenSetIncomplete(f"{key}/{case.case_id}: absent_criteria must be Grader-judged criteria")


def approved_grader_definition_keys() -> List[str]:
    """Every seeded curriculum definition with a Grader-judged criterion."""
    from app.assessment_curriculum import FOUNDATION_ASSESSMENTS, LEVEL1_EXPLAIN_BACK_ASSESSMENTS

    keys = [s["key"] for s in LEVEL1_EXPLAIN_BACK_ASSESSMENTS]
    keys += [s["key"] for s in FOUNDATION_ASSESSMENTS if any(c["method"] == "grader" for c in s["criteria"])]
    return sorted(set(keys))


# -- evaluating one case --------------------------------------------------------------------------------------------


def _evaluate(case: GoldenCase, judged: List[dict], round_status: str, judged_defs: List[dict]) -> List[str]:
    """Why (if at all) the candidate's findings do not match the case's expectation."""
    if round_status != GRADING_COMPLETE:
        return [f"the grading round did not complete cleanly ({round_status})"]
    reasons: List[str] = []
    by_key = {row["key"]: row for row in judged}
    for c in judged_defs:
        row = by_key.get(c["key"])
        if row is None:
            reasons.append(f"{c['key']}: no judgment was produced")
            continue
        runs = row.get("runs") or [row]
        findings = [r["finding"] for r in runs]
        if case.klass == CLEAR_PASS:
            if any(f != "met" for f in findings):
                reasons.append(f"{c['key']}: expected met, got {findings}")
            if any(r["confidence"] == "low" for r in runs):
                reasons.append(f"{c['key']}: low confidence on a clear pass")
        elif case.klass == CLEAR_FAIL:
            if any(f != "not_met" for f in findings):
                reasons.append(f"{c['key']}: expected not_met, got {findings}")
            if any(r["confidence"] == "low" for r in runs):
                reasons.append(f"{c['key']}: low confidence on a clear fail")
        elif c["key"] in case.absent_criteria and "met" in findings:
            reasons.append(f"{c['key']}: judged met although its ideas are wholly absent")
    if case.klass == BORDERLINE:
        runs_per_row = [row.get("runs") or [row] for row in judged]
        for slot in range(max((len(runs) for runs in runs_per_row), default=0)):
            findings = [runs[slot]["finding"] for runs in runs_per_row if len(runs) > slot]
            if findings and all(f == "met" for f in findings):
                reasons.append(f"run {slot + 1}: judged every criterion met on a borderline response")
    return reasons


class _GoldenRunner:
    def __init__(self, db: Session, user: User, adapter_factory: Optional[Callable]):
        self.db = db
        self.user = user
        self.grader = AssessmentGraderService(db, adapter_factory=adapter_factory)

    def run_case(self, definition: AssessmentDefinition, case: GoldenCase) -> tuple:
        judged_defs = _judged(definition)
        field_path = "fields.explanation"
        for c in definition.criteria:
            if c["method"] == "deterministic" and c.get("check", {}).get("field"):
                field_path = c["check"]["field"]
                break
        _root, _dot, name = field_path.partition(".")
        submission = {"fields": {name or "explanation": case.response}}
        draw = draw_challenge(self.db, definition, self.user.id, exclude=set())
        now = datetime.now(timezone.utc)
        attempt = AssessmentAttempt(
            user_id=self.user.id,
            definition_id=definition.id,
            origin=AssessmentOrigin.LEARNER_STARTED,
            # FINALIZED keeps the synthetic attempts out of the one-active-attempt index.
            status=AssessmentAttemptStatus.FINALIZED,
            pinned_versions={"golden_set": GOLDEN_SET_VERSION},
            fresh_required=False,
            challenge_seed=draw.seed if draw else None,
            challenge_instance=draw.instance if draw else None,
            draft={},
            submission=submission,
            submission_hash=sha256_hex(submission),
            input_manifest={},
            input_manifest_hash=sha256_hex({}),
            attestation={"declaration": "no_external_help"},
            started_at=now,
            submitted_at=now,
            finalized_at=now,
        )
        self.db.add(attempt)
        self.db.flush()
        # The deterministic stage is assumed met: the gate measures the Grader's judgment only.
        self.db.add(
            AssessmentResult(
                attempt_id=attempt.id,
                user_id=self.user.id,
                seq=1,
                round=0,
                result_kind=AssessmentResultKind.DETERMINISTIC,
                criteria=[
                    {
                        "key": c["key"],
                        "label": c["label"],
                        "method": "deterministic",
                        "required": c.get("required", True),
                        "check_type": c["check"]["type"],
                        "finding": "met",
                        "detail": "golden-set gate: platform checks are assumed met",
                        "facts": {},
                        "refs": [],
                    }
                    for c in definition.criteria
                    if c["method"] == "deterministic"
                ],
                facts={"golden_set": GOLDEN_SET_VERSION},
            )
        )
        self.db.commit()
        round_ = self.grader.grade(
            self.user,
            attempt,
            definition,
            crosscheck_required=AssessmentService._crosscheck_required(definition),
        )
        reasons = _evaluate(case, round_.judged, round_.status, judged_defs)
        models = (
            [r.get("provider_model_id") for r in ((round_.result.facts or {}).get("runs") or [])]
            if round_.result
            else []
        )
        result = CaseResult(
            definition_key=definition.definition_key,
            case_id=case.case_id,
            klass=case.klass,
            origin=case.origin,
            passed=not reasons,
            reasons=reasons,
            grading_status=round_.status,
            findings={
                row["key"]: [r["finding"] for r in (row.get("runs") or [row])] for row in round_.judged
            },
            models=models,
        )
        return result, attempt.grader_agent_version_id


# -- the gate --------------------------------------------------------------------------------------------------------------


def _current_definition(db: Session, key: str) -> Optional[AssessmentDefinition]:
    return (
        db.execute(
            select(AssessmentDefinition)
            .where(
                AssessmentDefinition.definition_key == key,
                AssessmentDefinition.status == AssessmentDefinitionStatus.PUBLISHED,
            )
            .order_by(AssessmentDefinition.version.desc())
        )
        .scalars()
        .first()
    )


def run_golden_gate(
    db: Session,
    user: User,
    *,
    adapter_factory: Optional[Callable] = None,
    required_keys: Optional[Iterable[str]] = None,
    definition_keys: Optional[Iterable[str]] = None,
    authored: Optional[Dict[str, List[Dict[str, Any]]]] = None,
) -> GoldenGateReport:
    """Run the candidate Grader configuration against the golden set.

    ``required_keys`` are the approved definitions that MUST be covered (default: every
    seeded curriculum definition with a Grader-judged criterion); ``definition_keys``
    narrows what is run (a narrowed run can never be release-ready if it leaves a
    required definition uncovered).
    """
    required = sorted(set(required_keys if required_keys is not None else approved_grader_definition_keys()))
    wanted = sorted(set(definition_keys)) if definition_keys is not None else required
    runner = _GoldenRunner(db, user, adapter_factory)

    cases: List[CaseResult] = []
    definitions: Dict[str, Dict[str, Any]] = {}
    covered: List[str] = []
    reasons: List[str] = []
    version_ids = set()
    for key in wanted:
        definition = _current_definition(db, key)
        if definition is None:
            definitions[key] = {"covered": False, "reason": "no published definition"}
            reasons.append(f"{key}: no published definition to gate")
            continue
        try:
            golden = golden_cases(definition, authored)
        except GoldenSetIncomplete as exc:
            definitions[key] = {"covered": False, "reason": str(exc)}
            reasons.append(str(exc))
            continue
        results = []
        for case in golden:
            result, version_id = runner.run_case(definition, case)
            version_ids.add(version_id)
            results.append(result)
        cases.extend(results)
        covered.append(key)
        definitions[key] = {
            "covered": True,
            "definition_version": definition.version,
            "content_hash": definition.content_hash,
            "cases": len(results),
            "passed": sum(1 for r in results if r.passed),
            "release_ready": all(r.passed for r in results),
        }
        reasons.extend(f"{r.definition_key}/{r.case_id}: {why}" for r in results for why in r.reasons)

    missing = [k for k in required if k not in covered]
    reasons.extend(
        f"{k}: an approved definition was not covered by this run" for k in missing if k not in wanted
    )
    version_ids.discard(None)
    candidate: Dict[str, Any] = {"grader_agent_version_ids": sorted(version_ids)}
    for version_id in version_ids:
        version = db.get(AgentVersion, version_id)
        prompt = db.get(PromptVersion, version.prompt_version_id) if version else None
        candidate.update(
            {
                "model_policy": version.model_policy if version else None,
                "prompt_sha256": hashlib.sha256(prompt.content.encode()).hexdigest() if prompt else None,
            }
        )
    candidate["provider_models"] = sorted({m for c in cases for m in c.models if m})
    ready = bool(cases) and not missing and all(c.passed for c in cases) and not reasons
    return GoldenGateReport(
        golden_set_version=GOLDEN_SET_VERSION,
        grading_contract_version=GRADING_CONTRACT_VERSION,
        candidate=candidate,
        coverage={"required": required, "covered": sorted(covered), "missing": missing},
        definitions=definitions,
        cases=cases,
        release_ready=ready,
        reasons=reasons,
    )


def render(report: GoldenGateReport) -> str:
    return json.dumps(report.to_json(), indent=2, sort_keys=True, default=str)
